### ISSUE TITLE
Parts list and instructions

### ISSUE THREAD

**Issue by h3xx** [TristanTrim/asetniop-keyboard#1]
I'd love to attempt to replicate what you did, but the instructions are kind of sparse. Having the model files for the ergonomic 3D-printed sections is great, but what I'd like to know is:

* How are the rows of keyboard keys constructed? What parts are they assembled from? Can you buy them pre-assembled? (I'm having trouble googling because I don't even know what they're called)
* What model of Arduino board did you use? I'd assume it was a USB-capable one, but it would be helpful to have a CPU model.
* From how you coded the Arduino board's logic, what's the wiring diagram supposed to look like?

**Comment by TristanTrim** [comment]
Thanks! I'll try and fix up the instructions based on your questions.
The keys are Cherry MX browns. You can buy them, but it may be hard to find someone selling only 8. You will probably need to get keycaps separately unless you want to print them. I found printing good quality ones difficult. They are set into a 3d printed board.
You could use any kind of switch if you wanted to make your own way to mount them. I like the browns, but I think it would be neat to try mouse click buttons.
The board is a teensyduino. I'll post the exact model tomorrow.
The wiring is extremely simple, just pins to keys to ground. I'll do up a diagram tomorrow.
Do you know how to type asetniop yet? You can practice online. (but not with my extended programmer chords.)

**Comment by TristanTrim** [comment]
I added a poorly drawn wiring diagram and bill of materials to the README.md

If you're still having any trouble let me know.

**Comment by h3xx** [comment]
I ordered a custom laser-cut plate from here: http://builder.swillkb.com/

If you use the simple `["a","s","e","t"]` as the input for the plate layout, you can order a custom-made 4-key plate for use in the project, possibly replacing the `plate.stl` part.

It doesn't have the screw holes, but it's made of metal which might provide more key stability. I'll let you know how this works out.
